package util;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;

/**
 * PDF Page Event Helper for iText 5.
 * Handles automatic header/footer rendering and "Page X of Y" pagination
 * on every page of the generated PDF document.
 * 
 * Header and footer text are sourced from web.xml context parameters:
 *   - report.header → "Active Learning, Inc. — Internship Learning Tracker"
 *   - report.footer → "Confidential | Generated by ICS2609 System"
 * 
 * @author Member 3 — DBMS 3 + PDF Reports
 */
public class PDFEventHelper extends PdfPageEventHelper {

    private final String headerText;
    private final String footerText;
    private PdfTemplate totalPagesTemplate;
    private BaseFont baseFont;

    private static final float FONT_SIZE_HEADER = 9f;
    private static final float FONT_SIZE_FOOTER = 8f;
    private static final float MARGIN_OFFSET = 30f;

    private int totalPages = 0;

    /**
     * Constructor — receives branding strings from web.xml context parameters.
     * @param headerText The report header string (from report.header context-param)
     * @param footerText The report footer string (from report.footer context-param)
     */
    public PDFEventHelper(String headerText, String footerText) {
        this.headerText = (headerText != null) ? headerText : "Active Learning, Inc.";
        this.footerText = (footerText != null) ? footerText : "Confidential";
    }

    /**
     * Called when the document is first opened.
     * Initializes the template placeholder for total page count ("Y" in "Page X of Y").
     */
    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {
        try {
            baseFont = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            // Template that will hold the total page number — filled in onCloseDocument()
            totalPagesTemplate = writer.getDirectContent().createTemplate(50, 16);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Called at the end of every page.
     * Draws the header (top-center) and footer (bottom with "Page X of Y").
     */
    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        if (baseFont == null) return;

        PdfContentByte canvas = writer.getDirectContent();
        Rectangle pageSize = document.getPageSize();
        float pageWidth = pageSize.getWidth();

        // Track the highest page number reached
        totalPages = writer.getPageNumber();

        // ── HEADER (Top Center) ──────────────────────────────────────
        Font headerFont = new Font(Font.FontFamily.HELVETICA, FONT_SIZE_HEADER, Font.BOLD, new BaseColor(80, 80, 80));
        Phrase headerPhrase = new Phrase(headerText, headerFont);
        ColumnText.showTextAligned(
            canvas,
            Element.ALIGN_CENTER,
            headerPhrase,
            pageWidth / 2,
            pageSize.getTop() - 20,
            0
        );

        // ── FOOTER LEFT (Branding) ──────────────────────────────────
        Font footerFont = new Font(Font.FontFamily.HELVETICA, FONT_SIZE_FOOTER, Font.NORMAL, new BaseColor(130, 130, 130));
        Phrase footerPhrase = new Phrase(footerText, footerFont);
        ColumnText.showTextAligned(
            canvas,
            Element.ALIGN_LEFT,
            footerPhrase,
            document.leftMargin(),
            pageSize.getBottom() + 15,
            0
        );

        // ── FOOTER RIGHT (Page X of Y) ─────────────────────────────
        int currentPage = writer.getPageNumber();
        String pageText = "Page " + currentPage + " of ";
        float textWidth = baseFont.getWidthPoint(pageText, FONT_SIZE_FOOTER);

        // Write "Page X of "
        Font pageFont = new Font(Font.FontFamily.HELVETICA, FONT_SIZE_FOOTER, Font.NORMAL, new BaseColor(130, 130, 130));
        Phrase pagePhrase = new Phrase(pageText, pageFont);
        float xPos = pageWidth - document.rightMargin() - textWidth - 30;
        float yPos = pageSize.getBottom() + 15;

        ColumnText.showTextAligned(
            canvas,
            Element.ALIGN_LEFT,
            pagePhrase,
            xPos,
            yPos,
            0
        );

        // Add the template placeholder for total pages right after "Page X of "
        canvas.addTemplate(totalPagesTemplate, xPos + textWidth, yPos);
    }

    /**
     * Called when the document is closed (after all pages are written).
     * Fills in the total page count template so every page shows the correct "Page X of Y".
     */
    @Override
    public void onCloseDocument(PdfWriter writer, Document document) {
        if (baseFont == null || totalPagesTemplate == null) return;

        // If for some reason no pages were created, default to 1
        if (totalPages <= 0) totalPages = 1;

        totalPagesTemplate.beginText();
        totalPagesTemplate.setFontAndSize(baseFont, FONT_SIZE_FOOTER);
        totalPagesTemplate.setColorFill(new BaseColor(130, 130, 130));
        totalPagesTemplate.showText(String.valueOf(totalPages));
        totalPagesTemplate.endText();
    }
}
